site_name: {repo_name}
site_description: ...
site_author: {owner_name}
site_url: https://{owner_name}.github.io/{repo_name}
repo_name: {owner_name}/{repo_name}
repo_url: https://github.com/{owner_name}/{repo_name}
edit_uri: blob/main/docs

theme:
  name: material

  features:
    - content.code.annotate

markdown_extensions:
  # mathjax
  - pymdownx.arithmatex:
      generic: true

  # syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: 'index.md'   