name: initialize repo

on: [ "push" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.repository, 'template')"

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: initialization
        run: |
          python init.py ${{ github.repository }}
          rm init.py
          rm .github/workflows/init.yaml
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "auto initial commit"
          git push