name: mkdocs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    if: "!(contains(github.repository, 'template') || contains(github.event.head_commit.message, 'initial commit'))"

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Render html files
        run: |
          pip install hatch
          hatch run docs:build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload "site" repository
          path: 'site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4