name: pytest

on: [ "push" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!(contains(github.repository, 'template') || contains(github.event.head_commit.message, 'initial commit'))"

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: test
        run: |
          pip install hatch
          hatch run tests:pytest
